### ISSUE TITLE
Seemingly random crashes in applyGradientMask:animated:

### ISSUE THREAD

**Issue by ckaik** [cbpowell/MarqueeLabel-Swift#13] opened 2015-10-27 09:42 UTC
Hi,

I've been using MarqueeLabel-Swift for the first time in the past few days. Unfortunately it seems like it's causing my app to crash. The crash is not consistent at all to reproduce, this is the first time I caught it in the debugger. I'm not sure what exactly is happening here or if it's even an issue with MarqueeLabel-Swift or maybe tvOS itself.

The call stack looks like this:

![screen shot 2015-10-27 at 10 22 53](https://cloud.githubusercontent.com/assets/5980743/10754254/d25bdc50-7c96-11e5-96e8-ffb4ee205fe1.png)

The Exception breakpoint is fired at this line: 

[MarqueeLabel.swift#L709](https://github.com/cbpowell/MarqueeLabel-Swift/blob/9bde55ea0459a8ec3dbffc642df0a9ddbd385684/Classes/MarqueeLabel.swift#L709)

**Comment by cbpowell** [comment] 2015-11-01 18:26
Weird, always on that line? (Side note, I edited your post to refer to the line you originally linked - the line numbers changed in the recent update)

Based on the call stack it would seem like the issue is in the `CALayer_setter_kCAValueCopiedPointer` call, but I guess that could still be something MarqueeLabel is doing.

The only change that immediately jumps to mind is to try changing that segment of code to:

``` swift
// Set up colors
let transparent = UIColor.clearColor().CGColor
let opaque = UIColor.blackColor().CGColor
let colors = [opaque, opaque, opaque, opaque]  // Add this line
// ...
// Start with default (no fade) locations
gradientMask.colors = colors  // Change (the former) line 709 to this
```

Since the error seems to be in copying pointers, this could maybe switch up when things get copied?

**Comment by ckaik** [comment] 2015-11-01 18:36
Hi,

When I was able to catch the crash in the debugger (since it's extremely ~~difficult~~ random to reproduce I only caught it two times) it was on that line.

Also, the exception mentions "[NSCFType doubleValue]: selector not recognized" (or something similar, definitely says doubleValue though and a type I don't recognize). This is weird since my code never calls doubleValue for anything, neither does MarqueeLabel.

I'm gonna try out your suggestion as soon as I can, thanks for replying though!

**Comment by cbpowell** [comment] 2015-11-01 18:50
Searching a bit for NSCFType seems to bring up a few issues related to memory management - i.e. something getting released too soon…which is something Swift/ARC should be doing for us in this reasonably simple code.

The change I suggested could potentially change up the retain/release points though, so let me know how it works! Also I came across [this SO answer](http://stackoverflow.com/questions/5236624/what-is-this-ios-exception-with-nscftype), and the accepted answer points out some helpful breakpoints to add to maybe catch it more often.

**Comment by AlexeyS** [comment] 2015-11-06 16:19
Hi! Got the same crash. Looks pretty rare and random. I happens for me on tvOS also. On cell reuse I reset label text and get this crash. I'm pretty sure that label itself is not being released on reuse...

![screen shot 2015-11-06 at 11 16 07 am](https://cloud.githubusercontent.com/assets/50188/11001900/d1a3f7c8-8477-11e5-9513-d79f6ee39fdc.png)

**Comment by ckaik** [comment] 2015-11-06 16:22
Note: I'm also using the Label in UICollectionView subclasses if that's worth anything. 

Unfortunately I couldn't try out your idea yet.

**Comment by cbpowell** [comment] 2015-11-06 17:25
Interesting, I might need to review the way the gradient mask layer is handled in relation to a cell reuse situation.

**Comment by manuelolmos** [comment] 2015-11-14 13:41
Hi, I'm also experiencing the same issue and it's not random in iOS8, it happens every time. An easy way to catch is to add an [Exception breakpoint](http://stackoverflow.com/a/14767076/1245203)

These two lines are the ones that cause the crash. 

```
gradientMask.colors = [opaque, opaque, opaque, opaque]
gradientMask.locations = [0.0, 0.0, 1.0, 1.0]
```

I had to comment both lines to avoid the crash. Could you find any solution to this problem?

Regards
Manuel.

**Comment by cbpowell** [comment] 2015-11-14 16:53
@manuelolmos Are you also using MarqueeLabel inside something that reuses views (i.e. table view or collection view)?

**Comment by manuelolmos** [comment] 2015-11-14 20:15
@cbpowell it's just inside a UIView. It's just happening with iOS8, it works fine with iOS9.

**Comment by cbpowell** [comment] 2015-11-28 23:56
Haven't made much progress on this over the holiday (for me) - are you guys setting anything in particular for the string during these crashes, like an empty string? What are you using for fade length? @fletcher89, @AlexeyS - were these in the tvOS simulator?

@manuelolmos Is that with any particular iOS 8 version? Does the demo crash for you on the same device/version? I only have the 8.4 simulator installed at the moment (and no iOS 8.x device), and don't get a crash.

**Comment by ckaik** [comment] 2015-11-30 07:24
@cbpowell Here are some of the facts 
- It happened on an actual Apple TV device
- No empty strings are being set
- When it happens, it happens right when the ViewController was being about to be presented
- Finally, those are the properties I set for the label:

``` swift
override func awakeFromNib() {
        super.awakeFromNib()

        titleLabel.fadeLength = 25.0
        titleLabel.scrollDuration = 10.0
        titleLabel.animationDelay = 3.0          
        titleLabel.holdScrolling = true
}
```

**Comment by manuelolmos** [comment] 2015-11-30 12:34
@cbpowell 
It happens when you have an empty string on iOS 8.4 or less simulators. With iOS 9.0+ it works fine.

**Comment by cbpowell** [comment] 2015-11-30 16:40
Thanks for the feedback! That let me reproduce it, at least on iOS 8.4 in the simulator.

So I think @manuelolmos is on to a potential solution of just removing those lines. I was able to prevent the crash by commenting out [the lines](https://github.com/cbpowell/MarqueeLabel-Swift/blob/ba10d36c81da98f42f78a8d32b95cdce1d577ea8/Classes/MarqueeLabel.swift#L719-L720) that set the initial `locations` and `colors` values to the gradient mask layer, and didn't notice any negative side effects. The "correct" locations and colors are set just a little later in the function anyway.

I was also able to prevent the crash by wrapping those lines (plus the surrounding) in a CATransaction that disabled the implicit animations:

``` swift
CATransaction.begin()
CATransaction.setValue(kCFBooleanTrue, forKey: kCATransactionDisableActions)
gradientMask.bounds = self.layer.bounds
// etc, etc...
// Start with default (no fade) locations
gradientMask.locations = [0.0, 0.0, 1.0, 1.0]
gradientMask.colors = colors
CATransaction.commit()
```

So it seems like some issue with setting those values and the implicit CALayer animation that occurs when those values are changed.

@fletcher89 / @AlexeyS - I'd suggest trying out the simple solution of just removing/commenting out those lines, and see if that fixes the issue for you guys?

**Comment by cbpowell** [comment] 2015-12-06 23:05
Pushed [release 2.3.6](https://github.com/cbpowell/MarqueeLabel-Swift/releases/tag/2.3.6) with the change suggested above.

**Comment by yonaskolb** [comment] 2015-12-23 05:32
I'm still getting a crash on tvOS on this line
`
gradientMask.bounds = self.layer.bounds
`
It only seems to happen when fadeLength is larger than 0, and items are being recycled quickly

**Comment by cbpowell** [comment] 2015-12-23 15:50
Hmm, well considering that disabling implicit animations helped on the other instances of crashing - @yonaskolb could you try modifying [the code here](https://github.com/cbpowell/MarqueeLabel-Swift/blob/master/Classes/MarqueeLabel.swift#L715-L720) to the below and see if it fixes your crash?

``` swift
// Configure gradient mask without implicit animations
CATransaction.begin()
CATransaction.setValue(kCFBooleanTrue, forKey: kCATransactionDisableActions)
gradientMask.bounds = self.layer.bounds
gradientMask.position = CGPointMake(CGRectGetMidX(self.bounds), CGRectGetMidY(self.bounds))
gradientMask.shouldRasterize = true
gradientMask.rasterizationScale = UIScreen.mainScreen().scale
gradientMask.startPoint = CGPointMake(0.0, 0.5)
gradientMask.endPoint = CGPointMake(1.0, 0.5)
CATransaction.commit()
```

Note the addition of the CATransaction calls.

**Comment by yonaskolb** [comment] 2016-01-03 23:26
Making that change helped but then crashed elsewhere. Wrapping that [section](https://github.com/cbpowell/MarqueeLabel-Swift/blob/master/Classes/MarqueeLabel.swift#L761-L762) in a CATransation as well fixed it!

**Comment by cbpowell** [comment] 2016-01-13 14:44
Thanks for the PR (#19) @yonaskolb - I was looking at this code too, and trying to decide how to best handle it. It definitely seems like the implicit CALayer animations are causing the crash, and those are undesired anyway. I'm trying to remember if adding that CATransaction will also disable the explicit CALayer animations, so I'll have to look into that.

**Comment by cbpowell** [comment] 2016-01-18 02:27
So I made some changes to this region of code in [v2.4.4](https://github.com/cbpowell/MarqueeLabel-Swift/releases/tag/2.4.4) and [v2.5.0](https://github.com/cbpowell/MarqueeLabel-Swift/releases/tag/2.5.0). Mostly it corrects the fact that the `applyGradientMask:animated:` function hasn't ever actually animated like I intended (oops).

I'm not sure it fixed the issue, but it's possible? In the mean time, I'm ordering a USB-C cable for my Apple TV so I can actually try and debug the issue.

**Comment by cbpowell** [comment] 2016-01-24 18:00
I received my USB-C cable, and thanks to the tvOS demo put together by @toshi0383 I was able to quickly try things out.

So far I haven't had a crash with the code as it stands today! But when reverting back to MarqueeLabel.swift as it stood on Nov 6th I get an immediate crash on launch - same exception @fletcher89 was getting about an unrecognized selector: `[__NSCFType doubleValue]`.

@fletcher89, @yonaskolb, @AlexeyS - please give the latest code a shot, and see if it fixes things for you! If it doesn't, I'll probably merge PR #19 as at least a temporary fix.

**Comment by yonaskolb** [comment] 2016-02-02 02:23
Seems to work for me

**Comment by cbpowell** [comment] 2016-02-07 20:26
I guess I'll close this one out. Let me know if you end up still having the same problem with the latest releases!

**Closed as completed by cbpowell** 2016-02-07 20:26 UTC
